# Generated by Django 6.0.5 on 2026-05-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_event_type_alter_submission_user_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('team', 'Team')], max_length=20),
        ),
    ]
